import { GetServerSidePropsContext, type NextPage } from "next";
import Head from "next/head";
import { Navbar } from "../components/Navbar";
import { getServerAuthSession } from "../server/auth";

export async function getServerSideProps(ctx: GetServerSidePropsContext) {
  const session = await getServerAuthSession(ctx);

  console.log(session);

  return {
    props: {
      session,
    },
  };
}

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className="flex min-h-screen flex-col items-center justify-center bg-gray-100">
        <div className="flex flex-col items-center">

          <span className="text-xl mb-2">Hi, I'm your new friend</span>
          <h1 className="text-5xl font-semibold">The Books</h1>
          <span className="text-2xl mt-8">
            I'm a website developed to help you with your self tasks.
          </span>
        </div>
      </main>
    </>
  );
};

export default Home;
